server:
  port: 8082

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/testdb?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8
    username: root
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver
  sql:
    init:
      mode: always

mybatis-plus:
  # mapper.xml文件所在路径，多个路径用逗号隔开
  mapper-locations: classpath*:/mapper/**/*.xml
  # 实体类所在包路径
  typeAliasesPackage: com.example.demo.entity
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
