#spring:
#  output:
#    ansi: enabled

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/testdb?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8
    username: root
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver

logging:
  file:
    name: user-service.log
#  level:
#    root: OFF

mybatis-plus:
  # mapper.xml文件所在路径，多个路径用逗号隔开
  mapper-locations: classpath*:/mapper/**/*.xml